### PR TITLE
Make `doctrine.fixtures.loader` public

### PR DESCRIPTION
**Pull request by ruudk**
I'm trying to get https://github.com/BehatExtension/DoctrineDataFixturesExtension to work with version 3.0 of this bundle.

It would help if this service was public, so that we can use this service to load all fixtures with all the dependencies.

## Related issue
https://github.com/BehatExtension/DoctrineDataFixturesExtension/issues/3

### CODE REVIEW

**Comment by ruudk** [comment]
Tests are failing because something else. Master seems broken.

**Comment by ruudk** [comment]
Master is failing because a wrong merge in https://github.com/doctrine/DoctrineFixturesBundle/pull/216#issuecomment-349077657

**Comment by ruudk** [comment]
Rebased on top of https://github.com/doctrine/DoctrineFixturesBundle/pull/223 to show that tests pass :)

**Comment by alcaeus** [comment]
@ruudk can you rebase on top of master please? Thanks!

**Comment by ruudk** [comment]
@alcaeus Done!

**Comment by alcaeus** [comment]
Thanks! 

FWIW, I can't figure out why we need to expose the loader for use in the extension you mentioned. Looking at the [service config](https://github.com/BehatExtension/DoctrineDataFixturesExtension/blob/master/src/Resources/config/services.xml#L47..L51), this might be a good opportunity to change the signature of the loader: instead of fetching services from the container, inject them properly using the service config. I don't see why we should expose services to the outside to cater to extensions that don't properly use the service container.

**Comment by ruudk** [comment]
@alcaeus Hmm, interesting. I'm gonna try to see if I can achieve it in a different way.

**Comment by ruudk** [comment]
My plan was to do the following: 

* When DoctrineFixturesBundle 3.0.2+ is installed, then grab all services from the Container tagged `doctrine.fixture.orm`. The issue is that the tags are only available during the building of the container. 

Since this Behat extension has no way to hook into that point (using an compiler pass), it becomes extremely hard to do this. 

Do you have another idea?

**Comment by ruudk** [comment]
Or did you mean something like this: https://github.com/BehatExtension/DoctrineDataFixturesExtension/pull/4

**Comment by alcaeus** [comment]
Even if you inject the loader, I wouldn't make the assumption that you want the behat extension to load the default fixtures.

**Comment by ruudk** [comment]
Any recommendations? My PR is not possible because Behat (+ extensions) run in a different container than the tests.

**Comment by wuethrich44** [comment]
@alcaeus I have a use case for this feature in my functional tests:

Before I execute my tests I would like to load all my fixtures in a sqlite database. I do that in the `setUp` of `KernelTestCase`:

```php
class FunctionalTestCase extends KernelTestCase
{
    private static $isDatabaseReady = false;

    protected function setUp()
    {
        if (!self::$isDatabaseReady) {
            self::bootKernel();

            $databaseInitializer = new DatabaseInitializer(self::$kernel->getContainer());
            $databaseInitializer->dropDatabase();
            $databaseInitializer->loadSchema();
            $databaseInitializer->loadFixtures();

            self::$isDatabaseReady = true;
        }
    }
...
```
Currently I have to look up all my fixtures with the `ContainerAwareLoader` and filepaths. It would be great if I could fetch the `SymfonyFixturesLoader` from the container and load my fixtures that way.

Any chance to get that merged?

**Comment by alcaeus** [comment]
If you need to make a service public, it's much better to add a public alias in a special `test.xml` service file that's only loaded in your test environment. In that case, you could even make the `DatabaseInitializer` a service within `test.xml` that you can fetch from the container. That way you can also properly wire arguments instead of relying on `$this->container->get(...)`.

Given that the original use-case (using the service within the Behat extension) is no longer given (the author also suggested to change the `FixtureLoader` class to receive proper service arguments, https://github.com/BehatExtension/DoctrineDataFixturesExtension/issues/3#issuecomment-349351080) I'm closing this pull request.

**Comment by wuethrich44** [comment]
@alcaeus Thanks for the hint. I could solve it with your explanation.

**Pull request closed without merging**
