### PR TITLE
Add documentation for DependentFixtureInterface

### PR DESCRIPTION
**Pull request by jbafford**
Resources/doc/index.rst gives an example using the OrderedFixtureInterface; the DependentFixtureInterface should also be described.

### CODE REVIEW

**Comment by lavoiesl** [comment]
Isn’t the documentation from the library enough? https://github.com/doctrine/data-fixtures#dependentfixtureinterface

**Comment by jbafford** [comment]
Apparently, I didn't think so at the time.

Especially since both of these packages are part of the Doctrine project, I think that if this bundle is going to provide documentation regarding how to use the data-fixtures package, it should be complete. Alternatively, don't provide any documentation at all on how to use data-fixtures, and instead, clearly point to the data-fixtures package documentation. (There are links to the data-fixtures package, but none that clearly say, Read The Documentation There.)

Otherwise, with a partial documentation set, you run the risk of confusing people who see this bundle as the entry point for the functionality, and don't think to look at the documentation for the main package.

At the time, I must have figured something along the lines of, "well, this is part of Doctrine, so clearly they're going to have all the relevant documentation here", and saw the lack of the DependentFixtureInterface documentation as an oversight. If I had seen the data-fixture's documentation at the time, this commit might instead just be along the lines of, "you can do this too, see the DependentFixtureInterface documentation for details". If you think that would be a better addition to the docs than this one, I can make a new PR for that.

**Comment by lavoiesl** [comment]
I agree with you that there should not be partial documentation. However, I believe it would be best to put the general documentation inside the general library and simply point to it. Complete examples of using DoctrineFixturesBundle could also become a Cookbook entry.

**Comment by stof** [comment]
I agree with @lavoiesl here. The documentation about features provided by the library should go in the library.
The bundle is only about exposing these features in the console of Symfony projects.

**Comment by guilhermeblanco** [comment]
This type of documentation should go to the library, closing.

**Pull request closed without merging**
