### PR TITLE
Improve the DX of the DoctrineFixturesBundle

### PR DESCRIPTION
**Pull request by javiereguiluz**
Doctrine is a great piece of software, but some developers from the Symfony community always tell us that sometimes it's too complex and cumbersome. That's why we'd like to improve the "developer experience" of Doctrine and smooth out some of its rough edges.

This pull request contains our first proposal to **simplify the creation of data fixtures**. As you can see, the idea is to provide an optional base class for data fixtures. Even if the code changes are minimal, the updated docs show all the simplifications that it allows.

Thanks for taking this PR into consideration!

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1:

**Comment by weaverryan** [comment]
+1 for me too! Makes life much easier for most people, but doesn't take anything away from the underlying architecture's flexibility.

**Comment by weaverryan** [comment]
Ping! This is a bit forward, but @stof would having another maintainer (me) be helpful to you? I don't know who else has maintainer access (it looks like Guilherme does, but his last merge was 2015).

**Comment by lyrixx** [comment]
This PR needs a rebase.

@stof Could you review it ? Thanks ;)

**Comment by fabpot** [comment]
I've just rebased this PR. I'm going to review it and merge.

**Pull request merged**
